FROM node:alpine3.21

RUN npm install -g bun

RUN apk add --no-cache openssl libc6-compat
WORKDIR /usr/src/app

ARG DATABASE_URL
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

# since bun can execute ts code, no need to build
CMD ["bun", "run", "start:web"]