FROM node:alpine3.21

RUN npm install -g bun

RUN apk add --no-cache openssl libc6-compat

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/ws ./apps/ws

RUN bun install
RUN bun run db:generate

EXPOSE 3001

# since bun can execute ts code, no need to build
CMD [ "bun", "start:ws"]