## Build the docker image
## push the docker image to dockerhub
## SSH into our VM and start the new image

name: Deploy the backend
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2
            
            - name: Docker login
              uses: docker/login-action@v2
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.backend
                push: true
                tags: saicharith2012/todo-app-backend:${{github.sha}}

            - name: Deploy to VM
              run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
                chmod 600 ~/ssh_key
                ssh -i ~/ssh_key -o StrictHostKeyChecking=no ${{secrets.SERVER_HOST}} -t "docker pull saicharith2012/todo-app-backend:${{github.sha}} && docker stop todo-app-backend && docker run --name todo-app-backend -d -p 3001:3001 -e DATABASE_URL=${{secrets.DATABASE_URL}} saicharith2012/todo-app-backend:${{github.sha}}"