## Build the docker image
## push the docker image to dockerhub
## SSH into our VM and start the new image

name: Deploy the frontend
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2
            
            - name: Docker login
              uses: docker/login-action@v2
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            
            - name: Set up Docker Buildx  # Add this step
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.frontend
                push: true
                tags: saicharith2012/todo-app-frontend:${{github.sha}}
                secrets: |
                  database_url=${{ secrets.DATABASE_URL }}
                        
            - name: Deploy to VM
              run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
                chmod 600 ~/ssh_key
                ssh -i ~/ssh_key -o StrictHostKeyChecking=no ${{secrets.SERVER_HOST}} -t "docker stop todo-app-frontend && docker rm todo-app-frontend && docker run --name todo-app-frontend -d -p 3000:3000 -e DATABASE_URL='${{secrets.DATABASE_URL}}' saicharith2012/todo-app-frontend:${{github.sha}} && docker image prune -af"        
