## Build the docker image
## push the docker image to dockerhub
## SSH into our VM and start the new image

name: Deploy the websocket server
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2
            
            - name: Docker login
              uses: docker/login-action@v2
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.websocket
                push: true
                tags: saicharith2012/todo-app-websocket:${{github.sha}}

            - name: Deploy to VM
              run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
                chmod 600 ~/ssh_key
                ssh -i ~/ssh_key -o StrictHostKeyChecking=no ${{secrets.SERVER_HOST}} -t "docker stop todo-app-websocket && docker rm todo-app-websocket && docker run --name todo-app-websocket -d -p 8081:8081 -e DATABASE_URL='${{secrets.DATABASE_URL}}' saicharith2012/todo-app-websocket:${{github.sha}} && docker image prune -af"        
